require('./lib/connectdb')
const express = require('express')
const app = express()
const bodyParser = require('body-parser').urlencoded({extended:false})
app.use(bodyParser)
const userRouter = require('./controllers/user.route')
const postRouter = require("./controllers/post.route")
const commentRouter = require("./controllers/comment.route")

app.use('/user',userRouter)
app.use('/post', postRouter)
app.use("/comment", commentRouter)
app.listen(3000,()=>{
    console.log('Server started!')
})